### ISSUE TITLE
Bug report  LiveDisplay The application Unable to uninstall

### ISSUE THREAD

**Issue by saraji-ali** [CarlosACepeda/LiveDisplay#32]
# Project Information

* Repository:  https://github.com/CarlosACepeda/LiveDisplay
* Project Name: LiveDisplay

# Expected behavior
When I try to uninstall the application, then the application must end in Mobile or Removed from Mobile

# Actual behavior

I have tried a lot of applications that do not remove or delete from my mobile phone

# How to reproduce

1-[Download ](https://github.com/CarlosACepeda/LiveDisplay/releases)the application
2- Now try uninstalling
3- see bug

* Browser/App version:  v0.8.0
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190506_141506](https://user-images.githubusercontent.com/50115498/57216861-eabc3280-6fa5-11e9-8c7c-b409a7d0d875.gif)

# My Github Account
https://github.com/facebook-786

**Comment by CarlosACepeda** [comment]
Hi there, many thanks for your report, this is not actual bug, but a normal behavior, In all the devices I've tested the System prompts the user to 'Deactivate this device administrator before unistall' either as a Dialog or as a Notification.
However as you show, this is not your case, maybe in the next update I'll prompt the user this message so it wont cause issues like this one, many thanks, if you have further comments, let me know, please, or may I close the issue?

Ah, the solution is to go to 'Device Administrators' then uncheck 'LiveDisplay', now you should be able to uninstall normally.

**Comment by CarlosACepeda** [comment]
Now In the 'help' option from the menu I display a dialog showing the user how to Uninstall the app, is my only way to indicate the user how to uninstall
