### ISSUE TITLE
No action is performed when I click on the 'Help' feature of the LiveDisplay app version 0.8.0

### ISSUE THREAD

**Issue by ChristophyBarth** [CarlosACepeda/LiveDisplay#33]
**Expected behavior**
- I expected the 'Help' feature to perform an action (maybe open an external link or a page in the app) when I click on it, so I could get to know more. 

---

**Actual behavior**
- The 'Help' feature does not perform any action when I click on it. 

---

**How to reproduce**
- Download, install and launch the latest version of the app
- Click on the three vertically arranged dots at the top right corner of the screen. 
- Observe the bug (no action is performed)

---

- App Version: v0.8.0
- Device: Gionee f100s 
- Operating System: 6.0

---

**Recording of the bug**

https://youtu.be/SqCdUef16wQ

**Comment by CarlosACepeda** [comment]
Hi there, thanks for your report
This is an already addressed 'bug'
Really it isn't a bug, only me being lazy, 😆 
The button was supposedly to show a dialog I haven't made yet, so in the next update it'll be solved. haha

**Comment by chrisbarth01** [comment]
But it presently a bug since the app has been released already.

**Comment by CarlosACepeda** [comment]
Now an action is performed, showing a simple dialog with instructions to uninstall the app, initially.
