### ISSUE TITLE
[Livedisplay][v0.8.0]The application crashes when I try to inactive time set

### ISSUE THREAD

**Issue by 44asad** [CarlosACepeda/LiveDisplay#36]
### Expected behavior

The application  should not crash when I click on  inactive time set.

### Actual behavior

the application is crash when I click on inactive time set.

### How to reproduce:
* Download the app and open it
* Then apply  setting option.
* Click the menu icon.
* click on notification & select naw inactive hours 
* see bug
### Recording Of The Bug
https://youtu.be/6gqffMh5wzk

1.Browser/App version: v0.8.0
2.Operating system: 5.0.1
3.Smartphone: Galaxy j2
### Logcat
<pre><code>E/AndroidRuntime(17414): FATAL EXCEPTION: main
E/AndroidRuntime(17414): Process: com.underground.livedisplay, PID: 17414
E/AndroidRuntime(17414): java.lang.NoSuchMethodError: no non-static method "Landroid/preference/PreferenceFragment;.getContext()Landroid/content/Context;"
E/AndroidRuntime(17414):   at mono.android.preference.Preference_OnPreferenceClickListenerImplementor.n_onPreferenceClick(Native Method)
E/AndroidRuntime(17414):   at mono.android.preference.Preference_OnPreferenceClickListenerImplementor.onPreferenceClick(Preference_OnPreferenceClickListenerImplementor.java:30)
E/AndroidRuntime(17414):   at android.preference.Preference.performClick(Preference.java:1162)
E/AndroidRuntime(17414):   at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:225)
E/AndroidRuntime(17414):   at android.widget.AdapterView.performItemClick(AdapterView.java:318)
E/AndroidRuntime(17414):   at android.widget.AbsListView.performItemClick(AbsListView.java:1166)
E/AndroidRuntime(17414):   at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
E/AndroidRuntime(17414):   at android.widget.AbsListView$3.run(AbsListView.java:3943)
E/AndroidRuntime(17414):   at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(17414):   at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(17414):   at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(17414):   at android.app.ActivityThread.main(ActivityThread.java:5912)
E/AndroidRuntime(17414):   at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17414):   at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(17414):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
E/AndroidRuntime(17414):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)</code></pre>

**Comment by CarlosACepeda** [comment]
ok, many thanks for your report, I'll be investigating this bug as I dont own a Lollipop device, hah.

**Comment by 44asad** [comment]
ok sir! thanks you

**Comment by CarlosACepeda** [comment]
Thanks to you, nice bug report.

**Comment by CarlosACepeda** [comment]
Found: Creating a Dialog that shows the clock to set the inactive time requires a Context, Im currently passing the Fragment Context using 'this.Context' which in Java is [this.getContext()](https://developer.android.com/reference/android/app/Fragment#getContext())
This method is not available until Android Marshmallow (api 23>)

**Comment by CarlosACepeda** [comment]
Fixed.
