### ISSUE TITLE
Bug report LiveDisplay  The application crashes when I click on Inactive hours

### ISSUE THREAD

**Issue by saraji-ali** [CarlosACepeda/LiveDisplay#37]
# Project Information

* Repository:  https://github.com/CarlosACepeda/LiveDisplay
* Project Name: LiveDisplay

# Expected behavior

When I click on the Inactive hour's option, these active hours should appear and the application should not be crashed.

# Actual behavior

After opening the application, I go to the setting and select the notification option there and when I click on Inactive hour's the app crashes.

# How to reproduce

1-[Download ](https://github.com/CarlosACepeda/LiveDisplay/releases)the app and open it
2-At the top right click 3 verticals dot
3- go to the setting 
4- open the notification option
5-click on Inactive hour's
6- see  app crashes

* Browser/App version: v0.8.0
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190511_162953](https://user-images.githubusercontent.com/50115498/57569287-87684100-73a7-11e9-9c74-b7a03ff809a7.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime(10644): FATAL EXCEPTION: main

E/AndroidRuntime(10644): Process: com.underground.livedisplay, PID: 10644

E/AndroidRuntime(10644): java.lang.NoSuchMethodError: no non-static method "Landroid/preference/PreferenceFragment;.getContext()Landroid/content/Context;"

E/AndroidRuntime(10644): 	at mono.android.preference.Preference_OnPreferenceClickListenerImplementor.n_onPreferenceClick(Native Method)

E/AndroidRuntime(10644): 	at mono.android.preference.Preference_OnPreferenceClickListenerImplementor.onPreferenceClick(Preference_OnPreferenceClickListenerImplementor.java:30)

E/AndroidRuntime(10644): 	at android.preference.Preference.performClick(Preference.java:1155)

E/AndroidRuntime(10644): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:225)

E/AndroidRuntime(10644): 	at android.widget.AdapterView.performItemClick(AdapterView.java:318)

E/AndroidRuntime(10644): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1169)

E/AndroidRuntime(10644): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3161)

E/AndroidRuntime(10644): 	at android.widget.AbsListView$3.run(AbsListView.java:3968)

E/AndroidRuntime(10644): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(10644): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(10644): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(10644): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(10644): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(10644): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(10644): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(10644): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by CarlosACepeda** [comment]
Please refer to #36 this has already been addressed and solved, many thanks for your report buddy,
it'll appear on the next update.
