### ISSUE TITLE
APKs no longer available at releases?

### ISSUE THREAD

**Issue by IzzySoft** [CarlosACepeda/LiveDisplay#58]
In the past you've attached the `.apk` files to their corresponding releases. Looks like you've stopped that a while ago. Could you please pick this up again? Not everybody has access to PlayStore, but this way everybody would have a chance to use the app :smiley: Thanks in advance!

**Comment by CarlosACepeda** [comment]
Hey!
Sorry for the late response, my project is dying hehe.
I actually didn't think anybody besides me wanted to use my app, but yeah, in the next release I will attach the Apk files or set up a Continuous Delivery of some sort!
Right now I don't have the apks for the latest builds.
So sorry about that!
Thanks for being interested!

**Comment by CarlosACepeda** [comment]
I am really trying to fix my codebase so it is easier for me to maintain because I wrote unmaintainable code! haha.
So far my knowledge has improved so I will try to be more consistent with releases and to maintain certain userbase because my most recent app still has bugs and, yeah.
Not that cool that I can't release a stable build, 😄 
So I hope to release something compelling and good for users soon! maybe the next two weeks or so

**Comment by IzzySoft** [comment]
Thanks a lot! Looking forward to that. Please let me know here when it's available. To give you further motivation: your app [is available here](https://apt.izzysoft.de/fdroid/index/apk/com.underground.livedisplay), with the APKs from this repo – which means users can install it using any F-Droid client and get notified about updates.

The "Tracking" anti-feature is there because the app includes MS AppCenter. If you think it's not that widely used anyway, you may consider dropping that library along the path to get rid of that flag :wink:

**Comment by CarlosACepeda** [comment]
Updated Laboratory branch with an initial work in the refactorization process, it is taking longer than I expect.
yet, the hard work is done, (moving code, renaming stuff, fixing code design choices so it is easier to maintain in the future)

**Comment by CarlosACepeda** [comment]
Fixed CI for Laboratory branch

**Comment by IzzySoft** [comment]
Thanks Carlos! So the next release should have an APK again? Can you please let me know when it's there (e.g. by closing this issue as "solution confirmed") so I can cross-check that it has been picked up as well?

**Comment by CarlosACepeda** [comment]
Fixed CD for Laboratory branch.
P.D
due to limitations the apk can be only distributed to contributors.
So I have to upload the apk manually in the release section for each push to this branch.
I can add you to the list of collaborators so you can receive a new build each time I push to Laboratory branch, instead of me uploading the apks to the release section.
At least for Laboratory branch builds, because I try to upload only stable releases in the master branch.
Thats when I upload apks in the releases section

**Comment by IzzySoft** [comment]
It's not just for me (or rather, not for me but for other users). Your app [is listed in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.underground.livedisplay) where it can be fetched and kept updated using any F-Droid client. My updater, which runs once a day, fetches the APKs from releases – so I'd need them there. A delay is of course acceptable: they'll be fetched when they're available, that's all :wink:

**Comment by CarlosACepeda** [comment]
Oh, that's perfect!
I will keep working, and update master branch to obtain a new release.
Until then I'll keep this issue open.

**Comment by IzzySoft** [comment]
Once that's done and updates are rolling again, be welcome to pick [a badge from here](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to my repo from the Readme :innocent:

**Comment by CarlosACepeda** [comment]
Continuous Delivery bound to Google Play Console, now it publishes automatically when a new push occurs in the branches.
Pushes to Laboratory will get published to the Beta Channel and pushes to Master will get published to the Production Channel.
In both cases, these versions will be available for everyone

Also, there's a new release (coming from Laboratory branch) so it is unstable.

https://github.com/CarlosACepeda/LiveDisplay/releases/tag/v1.0.0

**Comment by IzzySoft** [comment]
Thanks Carlos! But how to distinguish production builds from laboratory ones? The one you just linked would definitely be pulled as "stable" by my updater:

* tag name gives no indication, but is looking like a "final release" ("v1.0.0" instead e.g. "v0.9.9-dev" or "lab-0.9.9")
* the release is marked as "latest" (i.e. stable) instead of pre-release

It has no effect that the title in the description contains the term "preview". A human eye might spot that, an automatic updater is not looking at the description but at the tag :wink:

So may I kindly suggest to…

* mark the preview tag as pre-release
* attach the last stable APK to tag v0.9.5

? Thanks in advance!

PS: should it be not possible to automatically set the pre-release flag to the release, maybe you could use different tag names (pre- or suffixes), e.g. naming the laboratory ones `lab-<versionName>` and only the stable ones `v<versionName>`? I could then tell my updater to only pick the `v*` tags (and ignore all others).

**Comment by CarlosACepeda** [comment]
Yes, it could be, hehe.

**Comment by IzzySoft** [comment]
So may I ask what you decided for – so I can set it accordingly here in the configs?

**Comment by CarlosACepeda** [comment]
I will set a prefix for the tags next time I update a new release!
It seems easier for me, I can't edit tag v1.0.0
So yeah, I don't know how that affects you, 😬

**Comment by IzzySoft** [comment]
Sounds good, thanks! Please drop me a note then, so I can take a look and adjust the config on my end accordingly (fixing the updater to that prefix). Of course, if you already decided you could let me know in advance and I change that config right away, so it should then grab the update automatically.

**Comment by IzzySoft** [comment]
We weren't fast enough – looks like my updater just picked the 1.0.0 tonight. Is the debug flag (ApplicationDebuggable) intended?

**Comment by CarlosACepeda** [comment]
Sorry Izzy, I went offline few days, a loved one passed away, but I am back again, kinda, heh.
As for the flag, I actually don't know, I have to check this up because I didn't intend this, not even from the start of this project!

**Comment by IzzySoft** [comment]
Ugh, my sympathies then first! And take your time of course. Once you get that flag away, my updater with automatically notify me to remove the corresponding marker.

**Comment by CarlosACepeda** [comment]
I guess I know where the Application Debuggable comes from, and it'll be automatically solved once everything is pushed to 'master'
I set up the CD to compile the application in release mode, thus, removing this flag.
