### ISSUE TITLE
flagged as possible ransomware

### ISSUE THREAD

**Issue by magixtruct** [CarlosACepeda/LiveDisplay#62]
sophos flags this app as possible ransomware...
maybe you could find another method to hook into the lock mechanism without being device admin.
maybe like lock player or so?

**Comment by CarlosACepeda** [comment]
:O How come ransomware!
haha.
And no, in Android there's not a possible way to turn off the screen without using device admin.
One workaround I tried back in the day is to set the screen bright to 0, but this was really unstable and didn't work on all phones, so I abandoned that. :/

**Comment by CarlosACepeda** [comment]
Now I return the question, is possible to Sophos to think this application is NOT ransomware? 
haha
