### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by ghost** [CarlosACepeda/LiveDisplay#8]
![live display](https://user-images.githubusercontent.com/36993664/37881394-38ed7a7c-30a0-11e8-893b-c19e5dfa7581.jpg)

Hi, I have studied your work and I think a new design will make you more visible. I designed for you, I hope you like it and you want to use it. If you contact me here or from doganzr@gmail.com I can give you all the formats of the design free. If you want a change please specify.

![live display logo logotype icon](https://user-images.githubusercontent.com/36993664/37881400-4763520c-30a0-11e8-86c5-766d26fe4f27.jpg)

**Comment by CarlosACepeda** [comment]
Hi there! this is great!, the Application theme color is #726EBF so, maybe replace Red parts with this color, or a similar color, to make the Style follow the Theme designed in this app, but Overall is a great design, thank you, if your design is accepted then i will mention you in Readme and also in App: about section

**Comment by ghost** [comment]
![example](https://user-images.githubusercontent.com/36993664/37906849-03131af8-310c-11e8-9b88-721d71114f51.jpg)

Hi,

I'm glad you like it. I did what you wanted about the colors. If you like, I can send it for use in formats and sizes you want.

**Comment by CarlosACepeda** [comment]
Yeah, thanks, how can i contact you? Are the dpi sizes available? mdpi, hdpi, etc...?

**Comment by ghost** [comment]
Which do you like? Should I send them both?

**Comment by ghost** [comment]
My mail adress; doganzr@gmail.com

**Comment by CarlosACepeda** [comment]
Okay! your designs are cool, i'll make the changes soon, and give you credit. 👍 🖌

**Comment by CarlosACepeda** [comment]
@Yasujizr Have you checked? In the latest release I did you appear mentioned, again thanks for your help.
